import { createPagesFunctionHandler } from '@remix-run/cloudflare-pages';

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore - the server build file is generated by `remix vite:build`
// eslint-disable-next-line import/no-unresolved
import { getLoadContext, type EnvWithDrizzle } from '../load-context';

export const onRequest = createPagesFunctionHandler<EnvWithDrizzle>({
	build: () => import('../build/server/index.js'),
	getLoadContext,
});
